"""modify PK to init

Revision ID: 69518c174280
Revises: 6a727170d9e1
Create Date: 2026-02-19 15:00:32.448551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69518c174280'
down_revision: Union[str, Sequence[str], None] = '6a727170d9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regioes_ibge',
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.Column('cod_regiao', sa.String(), nullable=False),
    sa.Column('nome_regiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_regiao')
    )
    op.create_table('estados_ibge',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nome_estado', sa.String(), nullable=False),
    sa.Column('cod_estado', sa.String(), nullable=False),
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_regiao'], ['regioes_ibge.id_regiao'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('cod_estado'),
    sa.UniqueConstraint('nome_estado')
    )
    op.create_table('munícipios_ibge',
    sa.Column('id_municipio', sa.String(), nullable=False),
    sa.Column('nome_municipio', sa.String(), nullable=False),
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('microrregiao', sa.PickleType(), nullable=False),
    sa.Column('regiao_imediata', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['estados_ibge.id_estado'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.drop_table('tb_sor_estados_ibge')
    op.drop_table('munícipios')
    op.drop_table('tb_sor_regioes_ibge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_sor_regioes_ibge',
    sa.Column('id_regiao', sa.INTEGER(), nullable=False),
    sa.Column('cod_regiao', sa.VARCHAR(), nullable=False),
    sa.Column('nome_regiao', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id_regiao')
    )
    op.create_table('munícipios',
    sa.Column('id_municipio', sa.VARCHAR(), nullable=False),
    sa.Column('nome_municipio', sa.VARCHAR(), nullable=False),
    sa.Column('cod_estado', sa.INTEGER(), nullable=False),
    sa.Column('microrregiao', sa.BLOB(), nullable=False),
    sa.Column('regiao_imediata', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['tb_sor_estados_ibge.id_estado'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_table('tb_sor_estados_ibge',
    sa.Column('id_estado', sa.INTEGER(), nullable=False),
    sa.Column('nome_estado', sa.VARCHAR(), nullable=False),
    sa.Column('cod_estado', sa.VARCHAR(), nullable=False),
    sa.Column('id_regiao', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_regiao'], ['tb_sor_regioes_ibge.id_regiao'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('cod_estado'),
    sa.UniqueConstraint('nome_estado')
    )
    op.drop_table('munícipios_ibge')
    op.drop_table('estados_ibge')
    op.drop_table('regioes_ibge')
    # ### end Alembic commands ###
